### PR TITLE
@amfleming  => Working software for October 7th.

### PR DESCRIPTION
**Pull request by dblock**
@amfleming, what do you think about this?

### CODE REVIEW

**Comment by amfleming** [comment]
Might make sense to put the `until now` clause before the `Oct 7` heading, to make it really clear that those things were due in the past (not Oct 7)

I'd also put `a working first story with automated tests` into the pre-Oct 7 bucket

Then 

# Oct 7th - CI Checkpoint

To earn the point for this checkpoint your project needs to have
1. A project README
2. A working first story with automated tests
3. Continuous integration with a badge on the Github project
4. Continuous deployment to the cloud that happens automatically with every successful build

Verifying (1) and (3) are straightforward for the TA's

What would the logistics of verifying (4) look like? 
For the iPhone-app teams using back-ends like parse and deployment via AppStore - what is their CI requirement?

**Comment by dblock** [comment]
@amfleming Updated quite a bit, re-read.
- I pulled some things earlier and added a different milestone for October 14th. It would be cool to have the students convince another student to present for them, so I put that in.
- Automated tests for iOS are not a problem, we've been doing this forever. Check out for example https://github.com/artsy/eigen that uses Circle-CI or https://github.com/dblock/ARASCIISwizzle for Travis-CI. All free.

**Comment by amfleming** [comment]
Nice - this is a _much better_  and the clear deliverables are a win
- Students may see mandatory recruitment of other students for the Alpha demo as unfar
- I think the schedule as it is now may result in demo-fatigue.  Consider that it took 90 mins to get through 20 preso's, leaving only 1h for class after demos.  Probably one more all-class demo before the final presentations is all that the class has patience for
- Logistics are hard!   Any tricks (like the _green github_) button that make TA verification of deliverables is a huge win

**Comment by dblock** [comment]
I'm going to merge this, and lets iterate further on top.

**Pull request merged**
