### PR TITLE
Adding myself!

### PR DESCRIPTION
**Pull request by brunnoattorre**

### CODE REVIEW

**Comment by brunnoattorre** [comment]
Added photo brunno-attorre.jpg 
Added brunno-attorre.md under people folder
Added myself to the README.md

**Comment by dblock** [comment]
Good job. I'd like you to _squash_ these commits (aka collapse these 4 commits into 1), before merging.

**Comment by brunnoattorre** [comment]
Done!

**Comment by dblock** [comment]
There's still a commit that's not yours, check out the diff here. I think there's a bit of a mess that can be undone somewhat easily. Looks like you've added "Bochen Wang" as well, but it's not you :)

It's easier to work on a branch, so to fix this you could do the following:

```
# create a new branch called add-bruno-old with all the changes
git checkout -b add-bruno-old

# back on master
git checkout master

# rewind a bunch of commits
git reset --hard HEAD~10

# add upstream if you haven't yet
git remote add upstream git@github.com:Cornell-CS5356-Fall2015/cs5356.git

# sync your master with upstream master
git pull upstream master

# force push master to your own fork
git push origin master -f

# create a new branch add-bruno
git checkout -b add-bruno

# merge changes on add-bruno-old, without committing them
git merge add-bruno-old --squash

# examine changes, make sure it's all good
git add .
git commit -m "..."
git push origin add-bruno
```

Then close this PR and open a new one from the add-bruno branch.

**Pull request closed without merging**
