### PR TITLE
add yihan-chen.md

### PR DESCRIPTION
**Pull request by yeehanchan**

### CODE REVIEW

**Comment by dblock** [comment]
You also should add a link to README, please. Also _squash_ multiple commits. Check out http://code.dblock.org/2015/08/31/getting-out-of-your-first-git-mess.html, it might be helpful.

**Comment by karnseth** [comment]
Hi Yihan,

Let me know if you need any help also. My email is listed on the course webpage.
- Karn

**Comment by yeehanchan** [comment]
Hey Karnseth,
I've pulled a request on github again but didn't see my profile showed on
the page. I wonder is there any problem I didn't solve?

Best,
Yihan

**Comment by dblock** [comment]
cc: @karnseth

**Comment by dblock** [comment]
I am closing this without merging, please reopen with ^^^. Thanks.

**Pull request closed without merging**
