### PR TITLE
profile added - Sindhu

### PR DESCRIPTION
**Pull request by sindhubr**

### CODE REVIEW

**Comment by dblock** [comment]
Please add a link to the README, make sure to squash your commits too.

**Comment by karnseth** [comment]
Hi Sindhu,

Let me know (email/slack) if you need any help with this. You can also look at http://code.dblock.org/2015/08/31/getting-out-of-your-first-git-mess.html

**Comment by dblock** [comment]
I am closing this without merging, please reopen with ^^^. Thanks.

**Comment by sindhubr** [comment]
Hi!
Thank you so much , will do it right away.
Regards,
Sindhu

On Wed, Sep 9, 2015 at 7:07 AM, Daniel Doubrovkine (dB.) @dblockdotorg <
notifications@github.com> wrote:

> Closed #109 https://github.com/Cornell-CS5356-Fall2015/cs5356/pull/109.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cornell-CS5356-Fall2015/cs5356/pull/109#event-404696040
> .

## 

Regards,
Sindhu BR

**Pull request closed without merging**
