### PR TITLE
Bochen Wang Student Profile

### PR DESCRIPTION
**Pull request by wbcustc**
Add my photo and .md file to the repository.

### CODE REVIEW

**Comment by dblock** [comment]
Thanks great job! I want to ask you to learn (Google 
, etc.) how to _squash_ these commits - basically combine these into one. Give it a try before I merge this? It's going to be confusing but is a little challenge.

**Comment by dspeiser** [comment]
You may also want to consider adding your name/link to the README.md file (in alphabetical order I suppose).

**Comment by dblock** [comment]
Yes, @D-Speiser is right, thanks for pointing this out.

**Comment by dblock** [comment]
You'll have to rebase the changes here and you should put your changes on a branch. If you can't figure it out, find a TA or me on Slack and we'll help you out!

**Comment by wbcustc** [comment]
I have rebased the changes. Now you mean i need to put it on my own branch
right?

2015年8月27日星期四，Daniel Doubrovkine (dB.) @dblockdotorg <
notifications@github.com> 写道：

> You'll have to rebase the changes here and you should put your changes on
> a branch. If you can't figure it out, find a TA or me on Slack and we'll
> help you out!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cornell-CS5356-Fall2015/cs5356/pull/10#issuecomment-135494370
> .

## 

Send from Gmail ios

**Comment by dblock** [comment]
Here's what I mean:

Your changes should be on a branch. You can achieve this by creating a branch from where you are now with `git checkout -b my-info`. 

Your `master` branch should be the same thing as this repository. You can achieve this by going onto that branch, resetting it a few commits back and updating from "upstream", so:

```
# go to the master branch
git checkout master

# register the upstream git repository with git as "upstream"
git remote add upstream git@github.com:Cornell-CS5356-Fall2015/cs5356.git

# rewind a bunch of commits (you created a branch my-branch-name so your changes are safe there)
git reset HEAD~10 --hard

# sync with upstream
git pull upstream master

# push changes to github, it's a force push since we did some history rewriting
git push origin master -f 
```

Now to your own branch, "my-info".

```
# got to the my-info branch
git checkout my-info

# rebase with master, so basically your changes on top of whatever is in master
git rebase master

# push to github
git push origin my-info
```

Make a pull request from the my-info branch. 

This looks like a lot, but trust me this will become second nature in time :)

**Pull request closed without merging**
