### PR TITLE
Update vitaly-shmatikov.md

### PR DESCRIPTION
**Pull request by shmatikov**
Added link to my page

### CODE REVIEW

**Comment by dblock** [comment]
That doesn't render as a link, make it markdown please like so:

```
[Cornell Homepage](http://www.cs.cornell.edu/~shmat)
```

Maybe add a photo - I like the one on your site? Thanks!

**Comment by dblock** [comment]
I take my comment back, it does render as a link automagically. Would love a photo though :)

**Comment by austinpilot** [comment]
shmatikov

**Comment by dblock** [comment]
Closed via https://github.com/Cornell-CS5356-Fall2015/cs5356/commit/3f4d0f4c22b6ad66713395cc8899e247a855e3f2.

**Pull request closed without merging**
