### PR TITLE
Added sleep regulation app

### PR DESCRIPTION
**Pull request by copila**
Hi Daniel,

I added a project description in the projects folder, and the projects name to the read me.

Thanks,
Claire

### CODE REVIEW

**Comment by dblock** [comment]
Can you squash these commits please? ;) Thanks.

**Comment by copila** [comment]
Sure? How do I do that, and why?

**Comment by dblock** [comment]
One of the commits makes a mess, the other one undoes it.

See http://code.dblock.org/2015/08/31/getting-out-of-your-first-git-mess.html

**Comment by dblock** [comment]
Closed in favor of https://github.com/Cornell-CS5356-Fall2015/cs5356/pull/137.

**Pull request closed without merging**
