### PR TITLE
File added for Rishav

### PR DESCRIPTION
**Pull request by kanoria**
File & photo added

### CODE REVIEW

**Comment by dblock** [comment]
Please also add a link to README. Make sure to _squash_ any multiple commits.

**Comment by dblock** [comment]
Almost there. Can you please rebase this against upstream and put your name in the list in alphabetical order? Thanks.

**Comment by dblock** [comment]
Also try to write a better description for this commit than "file added". You'll have to squash multiple commits too, see http://code.dblock.org/2015/08/31/getting-out-of-your-first-git-mess.html if you need help.

**Comment by karnseth** [comment]
Can be closed

**Pull request closed without merging**
