### PR TITLE
Added First User Story to Blockchain Gambling project

### PR DESCRIPTION
**Pull request by HarrisonGregg**

### CODE REVIEW

**Comment by dblock** [comment]
Cool. Lets not merge this - give a shot to a project management software instead, like Trello or Waffle.io (works on top of Github issues). Move the story into that system (as a card or an issue), link it from here!

**Comment by dblock** [comment]
Specifically about this story I think it's too big and ambitious for the first story. For one, it's two things: users can bet and bitcoins can be transferred. Downsize your expectations to one thing, maybe "users can place a bet" or "coins can be tossed".

**Comment by HarrisonGregg** [comment]
Added waffle.io link and first story link to Bitcoin Gambling project description.

**Comment by amfleming** [comment]
way to go - your story in Waffle.io looks great

**Pull request merged**
