### PR TITLE
Rename file

### PR DESCRIPTION
**Pull request by johnw335**

### CODE REVIEW

**Comment by dblock** [comment]
You need to _rebase_ this against `upstream/master`, and _squash_ these commits. See http://code.dblock.org/2015/08/31/getting-out-of-your-first-git-mess.html if you get stuck.

**Comment by johnw335** [comment]
Hey,

Sorry, it's been a while since I have used any git. I'm not exactly sure
how to squash the commits even after reading the article.

Thanks,
John

**Comment by dblock** [comment]
Please connect with @karnseth and he'll help you in-person.

**Comment by johnw335** [comment]
Do you have his email address?

Thanks!
John

**Comment by dblock** [comment]
@johnw335 Follow his link on https://github.com/Cornell-CS5356-Fall2015/cs5356/blob/master/people/karn-seth.md. But please use Slack, he's on it.

**Comment by dblock** [comment]
@karnseth Can you please connect with @johnw335 Thanks!

**Comment by dblock** [comment]
I am closing this without merging, please reopen with ^^^. Thanks.

**Pull request closed without merging**
