### PR TITLE
Added Brendan Ritter to the list of students

### PR DESCRIPTION
**Pull request by code-11**

### CODE REVIEW

**Comment by dblock** [comment]
There will be other Brendan's :) Please rename the JPG name to the same as your .md file name. _Rebase_ and _squash_ any multiple commits please.

**Comment by dblock** [comment]
Bump @code-11

**Comment by code-11** [comment]
I think I squashed correctly let me know if there is anything I have to do, especially in regards to that conflict message.

**Comment by dblock** [comment]
I merged this via https://github.com/Cornell-CS5356-Fall2015/cs5356/commit/5c8c4e169b65acffcd214f320ae139d7440c18bc.

It needed a rebase and a `git rm people/photos/Thumbs.db`. Otherwise all good.

**Pull request closed without merging**
