### PR TITLE
Add Liudan Xiao to student list

### PR DESCRIPTION
**Pull request by ny11tamias**

### CODE REVIEW

**Comment by dblock** [comment]
This is good. However, before I merge, I want to ask you to _squash_ these commits, basically making them into 1. Let us know if you need help with it!

**Comment by liudan30** [comment]
Hi Daniel,

I find that I need some help to squash the commits. I can squash it on my
local terminal, but in fact nothing change on the website, and I can not
push my result either... The more I tried, the things get worse. This is
the first time I use github.

Thanks a lot.

On Fri, Aug 28, 2015 at 3:35 PM, Daniel Doubrovkine (dB.) @dblockdotorg <
notifications@github.com> wrote:

> This is good. I want to ask you to *squash* these commits, basically
> making them into 1. Let us know if you need help with it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cornell-CS5356-Fall2015/cs5356/pull/23#issuecomment-135868104>
> .
>



-- 

Liudan Xiao

MS in Connective Media - Class of 2017

Cornell Tech

Cornell University | lx98@cornell.edu | 646-203-9865 |
www.linkedin.com/in/liudanCT

**Comment by ny11tamias** [comment]
Hi Daniel,

I just successfully squash these commits. Please check it.

Thanks a lot!

On Fri, Aug 28, 2015 at 3:35 PM, Daniel Doubrovkine (dB.) @dblockdotorg <
notifications@github.com> wrote:

> This is good. I want to ask you to _squash_ these commits, basically
> making them into 1. Let us know if you need help with it!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cornell-CS5356-Fall2015/cs5356/pull/23#issuecomment-135868104
> .

## 

Liudan Xiao

MS in Connective Media - Class of 2017

Cornell Tech

Cornell University | lx98@cornell.edu | 646-203-9865 |
www.linkedin.com/in/liudanCT

**Comment by dblock** [comment]
Great job, you got it.

Merged via https://github.com/Cornell-CS5356-Fall2015/cs5356/commit/faf0af99b95e3c14219356c0776ebda30d7e2204.

You should learn to work on a branch. Because I had to rebase the change on the upstream repository right now your master is out of sync. To fix this the easiest is:

```
git checkout master

# rewind 10 commits, losing changes
git reset HEAD~10 --hard

# update to latest
git pull upstream master

# force push
git push origin master -f
```

Next time before making any changes, begin with `git checkout -b new-branch-name`.

**Comment by ny11tamias** [comment]
Understand! Thank you very much.

On Sat, Aug 29, 2015 at 9:33 AM, Daniel Doubrovkine (dB.) @dblockdotorg <
notifications@github.com> wrote:

> Great job, you got it.
> 
> Merged via faf0af9
> https://github.com/Cornell-CS5356-Fall2015/cs5356/commit/faf0af99b95e3c14219356c0776ebda30d7e2204
> .
> 
> You should learn to work on a branch. Because I had to rebase the change
> on the upstream repository right now your master is out of sync. To fix
> this the easiest is:
> 
> git checkout master
> 
> # rewind 10 commits, losing changes
> 
> git reset HEAD~10 --hard
> 
> # update to latest
> 
> git pull upstream master
> 
> # force push
> 
> git push origin master -f
> 
> Next time before making any changes, begin with git checkout -b
> new-branch-name.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cornell-CS5356-Fall2015/cs5356/pull/23#issuecomment-135987736
> .

## 

Liudan Xiao

MS in Connective Media - Class of 2017

Cornell Tech

Cornell University | lx98@cornell.edu | 646-203-9865 |
www.linkedin.com/in/liudanCT

**Pull request closed without merging**
