### PR TITLE
add first story

### PR DESCRIPTION
**Pull request by jferdizzle**

### CODE REVIEW

**Comment by dblock** [comment]
Please rebase this against master. Thanks.

**Comment by jferdizzle** [comment]
my bad!

**Comment by amfleming** [comment]
This commit looks great

It seems your Trello is private... if I we can't see your story we can't give you the point

https://trello.com/deets1

**Comment by jferdizzle** [comment]
Hi Adam, I added you, Dan, and the TA's to Trello as members. It said yours is @adamfleming8. Did you not get in?

screen shot 2015-09-21 at 4 58 35 pm

**Comment by amfleming** [comment]
Ah - I am amfleming@gmail.com

**Comment by jferdizzle** [comment]
Should be all fixed.

**Pull request merged**
