### PR TITLE
Mengjue Wang Homework1 version2

### PR DESCRIPTION
**Pull request by MengjueW**

### CODE REVIEW

**Comment by dblock** [comment]
Lets try to mimic a bit what others are doing, rename these files to be lowercase and have dashes in them, so `Mengjue Wang.md` becomes `mengjue-wang.md`, etc. Also please try to _squash_ these commits, ie. combine them into 1.

**Comment by dblock** [comment]
Getting closer. I still would like these commits to be _squashed_ and this change needs to be _rebased_.  LMK if you need help.

**Comment by MengjueW** [comment]
I used "git rebase -i HEAD~2" to squash the two commits, but I didn't see any change on the repository.

**Comment by dblock** [comment]
Did you push them to github? `git push origin master -f`?

**Comment by dblock** [comment]
Bump @MengjueW

**Pull request closed without merging**
