### PR TITLE
Homework Completion

### PR DESCRIPTION
**Pull request by asheesh-agarwal**
Information page added for Asheesh Agarwal

### CODE REVIEW

**Comment by dblock** [comment]
Good, can you please _squash_ these commits?

**Comment by asheesh-agarwal** [comment]
I tried to squash the commits but I am not able to do it. Everytime I complete the rebase, the git status says that you have to pull the changes from GitHub and then once I pull it there are again two commits. :( 

I will check on this later today. Meanwhile if you have any advice for me?

**Comment by dblock** [comment]
This should be helpful: http://code.dblock.org/2015/08/31/getting-out-of-your-first-git-mess.html

**Comment by asheesh-agarwal** [comment]
Do not take this pull request, I am going to raise a new one.

**Pull request closed without merging**
