### PR TITLE
Added Team & Project Management Tool for MeetMe

### PR DESCRIPTION
**Pull request by anasb**
PS: Who should we add to our private Trello board? Thank you.

### CODE REVIEW

**Comment by anasb** [comment]
Hi, I'm still unclear about who to add to our Trello board? Should I just invite by email all the instructors?
Thanks

**Comment by dblock** [comment]
If the board is private, sure.

**Comment by anasb** [comment]
@dblock Done.

**Comment by dblock** [comment]
:+1:

**Pull request merged**
