### PR TITLE
Rebased and added files again for Srinivasa Teja.

### PR DESCRIPTION
**Pull request by trocker**
The article you shared was so helpful. I've been using git for years now but I never ever did a single rebase, mainly because I was able to get around with some hacks but I'm so glab I did it here! I get the idea now. Thanks!

I'm still not sure if the typical workflow involves deleting the previous pull request (a different one) or if we just leave it like that.
Also, if a change is requested in the present pull request, do I just make the change and commit? Will the pull request get updated automatically or do I need to do anything?

PS: I should've been more careful with copying Bill's file! Definitely embarrassing.

### CODE REVIEW

**Comment by dblock** [comment]
This is good. I can merge this and rebase myself but a commit _just_ went in. If you can rebase this it'd be great, as simple as `git checkout master`, `git pull upstream master`, `git checkout student-list`, `git rebase master`,... merge conflicts, then force push with `git push origin student-list -f`.

**Comment by dblock** [comment]
You can close the previous PR. In general you can push from branch1 to 2, with `git push origin b1:b2 -f`, this is what I do to update existing pull requests.

**Comment by trocker** [comment]
I just saw the new commit and that this branch has conflicts. Is this what happens in typical contribution? As in, when a developer submits a pull request and another dozen commits happen before his pull request is accepted, does he (usually) pull and push again? Because if he pushes again then there might be some other commits before the pull request is accepted right?

**Comment by trocker** [comment]
Wow, this is pretty cool! I just saw this branch become up-to-date.

**Comment by dblock** [comment]
Good, merging.

**Pull request merged**
