### PR TITLE
Adding Student Information - Shreyas

### PR DESCRIPTION
**Pull request by kshreyas91**

### CODE REVIEW

**Comment by dblock** [comment]
This looks good. Before I merge this I want you to try and "squash" these commits, basically make them into one. Google it, Lmk if you get stuck. You will also need to "rebase" your changes since there were other changes on this repository.

**Comment by dblock** [comment]
Oh and we'd love a picture too!

**Comment by kshreyas91** [comment]
Hey,

I have made the changes. LMK if it looks good now.
Should I be making another pull request ?

On Thu, Aug 27, 2015 at 1:03 PM, Daniel Doubrovkine (dB.) @dblockdotorg <
notifications@github.com> wrote:

> Oh and we'd love a picture too!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cornell-CS5356-Fall2015/cs5356/pull/14#issuecomment-135493811
> .

## 

Regards,
Shreyas

**Comment by dblock** [comment]
If you look at this pull request you'll notice that it brought with itself a whole slew of changes. You need to _rebase_ your pull request. It should look like just 1 commit here that's yours, right now it says 18 :)

**Comment by dblock** [comment]
Bump @kshreyas91.

**Comment by kshreyas91** [comment]
Hey.
This repository was a mess. I have deleted this, forked a new one and sent
another pull request that was accepted.

On Sunday, August 30, 2015, Daniel Doubrovkine (dB.) @dblockdotorg <
notifications@github.com> wrote:

> Bump @kshreyas91 https://github.com/kshreyas91.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cornell-CS5356-Fall2015/cs5356/pull/14#issuecomment-136138523
> .

## 

Regards,
Shreyas

**Comment by dblock** [comment]
You went the easy way :) Cool, lets just close it then.

**Comment by kshreyas91** [comment]
Thanks. Tried a lot and it just kept getting messier.

On Sunday, August 30, 2015, Daniel Doubrovkine (dB.) @dblockdotorg <
notifications@github.com> wrote:

> You went the easy way :) Cool, lets just close it then.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cornell-CS5356-Fall2015/cs5356/pull/14#issuecomment-136138885
> .

## 

Regards,
Shreyas

**Comment by dblock** [comment]
Appreciate you trying! It's not supposed to be easy :) Eventually this stuff becomes muscle memory and it's very important to experience the actual dev workflow by _doing_ it, especially getting in these hard to undo git situations.

**Comment by kshreyas91** [comment]
Realized that!
Next time if I fall into something similar, I will make sure I find my way
out successfully.

On Sunday, August 30, 2015, Daniel Doubrovkine (dB.) @dblockdotorg <
notifications@github.com> wrote:

> Appreciate you trying! It's not supposed to be easy :) Eventually this
> stuff becomes muscle memory and it's very important to experience the
> actual dev workflow by _doing_ it, especially getting in these hard to
> undo git situations.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Cornell-CS5356-Fall2015/cs5356/pull/14#issuecomment-136139179
> .

## 

Regards,
Shreyas

**Pull request closed without merging**
