### PR TITLE
Add trello link

### PR DESCRIPTION
**Pull request by johnw335**

### CODE REVIEW

**Comment by amfleming** [comment]
Looks good; can  you rebase onto master please?

**Comment by johnw335** [comment]
I did a git rebase origin master and then a git push. Is that all I needed
to do?

**Comment by dblock** [comment]
Likely. Make sure that there's 1 single commit here.

**Comment by johnw335** [comment]
Yeah, I only made one commit on that push. Is that all I need to do?

Thanks!
John

**Comment by dblock** [comment]
@johnw335 Not quite. Maybe @karnseth or @dagoch can help you in-person?

**Pull request closed without merging**
